[package]
name = "sequencer-relayer"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
async-trait = "0.1"
base64 = "0.21"
bech32 = "0.9"
hex = "0.4"
prost = "0.11"
prost-types = "0.11"
rs-cnc = { git = "https://github.com/astriaorg/rs-cnc.git" }
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.10"
structopt = "0.3"
tokio = { version = "1.24", features = [ "full" ] }
tracing = "0.1"
tracing-subscriber = "0.2.15"

[build-dependencies]
prost-build = "0.11"