apiVersion: v1
kind: ConfigMap
metadata:
  name: sequencer-relayer-celestia-env
  namespace: default
data:
  coins: "1000000000000000utia"
  validator_stake: "5000000000utia"
  chainid: "test"
  keyring_backend: "test"
  validator_key_name: "validator"
  # evm address corresponds to private key:
  # da6ed55cb2894ac2c9c10209c09de8e8b9d109b910338d5bf3d747a7e1fc9eb9
  evm_address: "0x966e6f22781EF6a6A82BBB4DB3df8E225DfD9488"
  home_dir: "/home/celestia"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sequencer-relayer-metro-env
  namespace: default
data:
  coins: "1000000000000000utick"
  validator_stake: "5000000000utick"
  chainid: "test"
  keyring_backend: "test"
  validator_key_name: "validator"
  # evm address corresponds to private key:
  # da6ed55cb2894ac2c9c10209c09de8e8b9d109b910338d5bf3d747a7e1fc9eb9
  evm_address: "0x966e6f22781EF6a6A82BBB4DB3df8E225DfD9488"
  home_dir: "/home/metro"
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2023-04-03T10:34:40Z"
  name: sequencer-relayer-stack
  labels:
    app: sequencer-relayer-stack-app
spec:
  # securityContext:
  #   runAsUser: 10001
  initContainers:
    - command:
      - /scripts/init-celestia-appd-podman.sh
      name: init-celestia-app
      image: "ghcr.io/astriaorg/celestia-app:v0.11.0"
      volumeMounts:
        - mountPath: /scripts/
          name: scripts-volume
          readOnly: true
        - mountPath: /home/celestia
          name: celestia-home
      envFrom:
        - configMapRef:
            name: sequencer-relayer-celestia-env
    - command:
      - /scripts/init-bridge-podman.sh
      name: init-bridge
      image: "ghcr.io/astriaorg/celestia-node:test-sha-07fa3e7"
      volumeMounts:
        - mountPath: /scripts/
          name: scripts-volume
          readOnly: true
        - mountPath: /home/celestia
          name: celestia-home
      env:
        - name: home_dir
          valueFrom:
            configMapKeyRef:
              name: sequencer-relayer-celestia-env
              key: home_dir
    - command:
      - /scripts/init-metro-podman.sh
      name: init-metro
      image: "ghcr.io/astriaorg/metro:0.0.2"
      volumeMounts:
        - mountPath: /scripts/
          name: scripts-volume
          readOnly: true
        - mountPath: /home/metro
          name: metro-home
      envFrom:
        - configMapRef:
            name: sequencer-relayer-metro-env
    - command:
      - /scripts/configure-metro-podman.sh
      name: configure-metro
      image: ghcr.io/tomwright/dasel:alpine
      env:
        - name: home_dir
          valueFrom:
            configMapKeyRef:
              name: sequencer-relayer-metro-env
              key: home_dir
      volumeMounts:
        - mountPath: /scripts/
          name: scripts-volume
          readOnly: true
        - mountPath: /home/metro
          name: metro-home
  containers:
    - name: celestia-app
      command: ["/scripts/start-celestia-appd-podman.sh"]
      image: "ghcr.io/astriaorg/celestia-app:v0.11.0"
      envFrom:
        - configMapRef:
            name: sequencer-relayer-celestia-env
      volumeMounts:
      - mountPath: /scripts/
        name: scripts-volume
        readOnly: true
      - mountPath: /home/celestia
        name: celestia-home
    - name: celestia-bridge
      command:
      - /scripts/start-bridge-podman.sh
      image: "ghcr.io/astriaorg/celestia-node:test-sha-07fa3e7"
      volumeMounts:
        - mountPath: /scripts/
          name: scripts-volume
          readOnly: true
        - mountPath: /home/celestia
          name: celestia-home
      envFrom:
        - configMapRef:
            name: sequencer-relayer-celestia-env
      ports:
        - containerPort: 26659
          name: bridge-svc
    - name: metro-sequencer
      command: ["/scripts/start-metro-podman.sh"]
      image: "ghcr.io/astriaorg/metro:0.0.2"
      ports:
        - containerPort: 1318
      volumeMounts:
        - mountPath: /scripts/
          name: scripts-volume
          readOnly: true
        - mountPath: /home/metro
          name: metro-home
      envFrom:
        - configMapRef:
            name: sequencer-relayer-metro-env
  restartPolicy: OnFailure
  volumes:
  - hostPath:
      path: /scripts
      type: Directory
    name: scripts-volume
  - emptyDir: {}
    name: celestia-home
  - emptyDir: {}
    name: metro-home
---
kind: Service
apiVersion: v1
metadata:
  name: sequencer-relayer-stack-service
spec: 
  selector:
    app: sequencer-relayer-stack-app
  ports:
    - name: sequencer-svc
      port: 1318
    - name: bridge-svc
      port: 26659
      targetPort: bridge-svc
---
