name: Build and Publish Docker image

# Trigger on pushes to master branch, new semantic version tags, and pull request updates
on:
  workflow_dispatch:
  push:
    branches:
      - "master"
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-alpha.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-beta.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-rc[0-9]+"
  # trigger on pull request updates when target is `master` branch
  pull_request:
    branches:
      - "master"

jobs:
  build-and-publish-latest:
    strategy:
      matrix:
        distroless_tag: [latest, debug]
    runs-on: ubuntu-latest
    steps:
      # Checking out the repo
      - uses: actions/checkout@v2
      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
      # Generate correct tabs and labels
      - name: Docker metadata
        id: metadata
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/astriaorg/sequencer-relayer
          tags: |
            # use suffix-less tags for non-debug distroless images
            type=ref,event=pr,enable=${{ matrix.distroless_tag == 'latest' }}
            type=semver,pattern={{major}}.{{minor}}.{{patch}},enable=${{ matrix.distroless_tag == 'latest' }}
            type=sha,enable=${{ matrix.distroless_tag == 'latest' }}
            # tag images with `-debug` that use debug distroless images
            type=ref,event=pr,suffix=-debug,enable=${{ matrix.distroless_tag == 'debug' }}
            type=semver,suffix=-debug,pattern={{major}}.{{minor}}.{{patch}},enable=${{ matrix.distroless_tag == 'debug' }}
            type=sha,suffix=-debug,enable=${{ matrix.distroless_tag == 'debug' }}
            # set latest tag for `master` branch, but never for images based on distroless debug
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/master' && matrix.distroless_tag == 'latest' }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          provenance: false
          push: true
          build-args: DISTROLESS_TAG=${{ matrix.distroless_tag }}
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
