name: Tests

on: [pull_request]

jobs:
  test:
    name: build-and-test
    strategy:
      matrix:
        go-version: [ 1.19.x ]
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - name: Clone Metro
        uses: actions/checkout@v2
        with:
          repository: histolabs/metro
          path: './metro'
      - name: Build Metro
        run: |
          cd metro && make install
          bash scripts/single-node.sh &
      - uses: actions/checkout@v2
      - name: Install stable
        run: rustup toolchain install stable
      - name: Build
        run: cargo build --all
      - name: Run tests
        run: cargo test --all

  fmt:
    name: fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: rustup component add rustfmt
      - uses: actions-rs/cargo@v2
        with:
          command: fmt
          args: --all -- --check

  clippy:
    name: clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: rustup component add clippy
      - uses: actions-rs/cargo@v2
        with:
          command: clippy
          args: --all --all-targets -- -D warnings
          