name: Tests

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  test:
    name: build-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@1.69.0
      - uses: Swatinem/rust-cache@v2
      - name: Install protoc
        uses: arduino/setup-protoc@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build tests
        run: cargo test --release --no-run
      - name: Run fast tests
        run: cargo test --release
      - name: create kubernetes in docker cluster
        uses: helm/kind-action@v1.5.0
        with:
          version: v0.18.0
          config: test_environment/cluster-config.yml
          kubectl_version: v1.27.1
      - name: install just
        uses: taiki-e/install-action@just
      - run: just deploy-ingress-controller
      - run: just perform-prepull
      - run: just wait-for-ingress-controller
      - run: just wait-for-prepull
      - name: Run slow tests
        run: cargo test --release -- --ignored

  fmt:
    name: fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@1.69.0
        with:
          components: rustfmt
      - name: run rustfmt
        run: cargo +nightly fmt --all -- --check

  clippy:
    name: clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@1.69.0
        with:
          components: clippy
      - uses: Swatinem/rust-cache@v2
      - name: Install protoc
        uses: arduino/setup-protoc@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - run: cargo clippy --all --all-targets -- -D warnings
